env:
  global:
    - secure: okQm9r+Ma+dyOT/5HrqYxVUN3S/G/tMnJfy1gRFAkYEAI2qPD7EYVUgCRCRLwi0yNIgWbBmRhlnKKmwDT8+p3Xgw0/DGWTdc1dFP2ajxhbH86bupdVVfvIxYGfuOIHWW38S6JTcCgHlHBP1P152w822MYAvBShXOORMsf3OMgmIvFS2wJAgIgYDqRY4oNUD9N4DDFq/RLRqdJjm7y9PYjYmulHxlS7f0438A6pDv7OpgSTnd6WFU3iwQaTbm+UVbsDFuH9VfzYQ4Znh5AVFW1gSxlda9oRCYMCOQA58+yO45DMPDmwXywAoWUyIYdYwuqEPQUGMl5TwbT6hBqyXtTVf+g1fFx7R7becsktlueYLUUXbA36Fa0/He54B1xuwLUX0aSBgEQh4r93YvQTX9P1zmtuoOiFOW5n+e1zIwmkq2cc/V8wGvd3cfocWqVy8RuOt0IjKApGKvV9RNWbjkWuodJhHx/vyspr1Ws/TaIu7nHC+XVRUIQAg7UpwTEDWz0DDp+GAJ4V78GL/yq7Sfwnq1fEegZKb+u/+mMSOP29EChuKhLNdCK1ALPOK1fP+9zVbb5clYSg3vtBzhckSLq6GyyhqREo4dv5uzKQPxCFdefUgc4kD8eyC8ekgJwSgCpgzy3ovb/jo/3YZkAqY/Pfge6mM/SnOf7tL+LmlJYOM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MinimalHostsBlocker
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
