env:
  global:
    - secure: rFWS+g9ENXpPbblISSppBjQoLhId7OY0x/aizjqLFgMYC5PvB7HQqCl6BsXKSnDMJ7GfBqOKzo8DBHl1eZZ4JkDkVN6M0TIeE/W3g1S7ZK445sqn+sWiTqSKinmu9gkr2w60hnUmXmExI8gQegp909Cl3EmXh3LKmrLSY05Wds44Tut5S4IComZlaQv/nWE3f7FPkalSes0pbaDvUsXz7hHvGZkbt6E1ZCAdrb/BKHP/fovOeJSC4+MX77aFU4i1ajDJES8bbmEW3AI+aoTe4CdzQSVgzHCk6yv6itocFdF31HQlOeDdQGqcy+XSR2HRU3+WkQNBwKsQefedIREWXgYbT0uWTpfzVM6KLzr3CHNyoHK+tPbNNWOjQgCkv1ZPm6lFBnsLs5WGPvyuCD8biepd8mOZAgsXCjuXibTQTm1f0avsdbStd9F383gmfF3OS5DrjAFKvKKo0A4IGiNxLdvbZzNl0g7JzBwtmdtFkyrnE+48q3n+N15Mu2a8pMGc0WteN5F32dUj0ePXq0ven28HQAtbl1768cHqtmJR18Uyxj0/IMD+o5XOl1E5R/gGGEy1WD5gtGrtq2HPGHQcci2HEwUEnLEF6Q54pT8UThsK76wGekUdcVQ/LsGJk4iesyxTTsuHKK0FaFc9ySqgnLHNE98EnpN9tzRjXXsgi3M=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MinimalHostsBlocker
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
