env:
  global:
    - secure: LcjzJf5w4iwuL15QttMiwGtwtgTpWB9XfGF2OB/OUmnHy3qDFXP6KSlRfzFjsHG3oAJJWTHOs1vI/ZiDEwyd87P61oe5Yu+n/jEldWFLJqqpTZFC2EO3YfpUfVQjDZpPYwn7JhJ083i66exXxMcgXfAvDlhgHo1y0YZqZmt+fLlRieEidLhf75G+RD4WPURZIDoaCEuxPeM6Lnz8bSxi/hj7Jw4PE6+Woz/H6dPaPDiunyDzl8+pYKCrrt92J5attSlnptpAMxUR2JHVPUlRF40dmXNzWUQ+Esl8rrXrEsAto6W6/11K7bOm4sqgFNWCxBENFD263K+WzErdjHEPwOPHkxL2OpWnxSYRO5xF6Vrb1BdUxgua0ZOAtW64LIASo/bYnWDnwYTiV7DeFD2r9LrpjFGASkgsqWfqlVIyq8vy2yewkc8jN1WPJdehbrlSoxmXN3L+SdF3VDhentq8VHDF8OvGqZSfBUp0hKIWQ0OhBgvnHeOyLj/uYe61ZkXQYxGDVMAd5Y56BZ7hAEdrOVrt07NzFmDqs5G0hNI7PyFvkizwrhvFcCWgp6vReLUhq4mY+mI2j5+VYrxIitZtj8BvOJtNpQvMov5C5lPRb/qOwtfoi3kTs766mM8cED9fizN0ks/dL/3sUo0mrTJBoZCqzFkbARIkx8fW6g4UHQM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MinimalHostsBlocker
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
