env:
  global:
    - secure: cVlyPXg66StsiqndQHnGdzdTfzysUfulWHQ6LCFLo38h22PI/xQLoXOq5xNaCSt3pyAeA/oJSDKgsxu+OvuebOidFFXb/ttADHYk6cs/lTbktYcvjcSqK9nvsJ/cauONdaH9e9ZfaWpBZQxU1C6pSE/ASs8A11vOixheDfz/YMpzA27zqd/I1mpZ34VJaz0ExuG4uccNywwsBmTmGuadRzt6rZw5NbA7qL1h8QlaU/SM9vbVhfQMaOAdlw+glxkREDAs4760sYv1t0LxNsgdGvYsFpeHrFE8rRzgelZx4En2INHsPpWTZgPem9ZeZkeJoxOCZPifi9hCtanUg2QKN5wizmuZReMdcRRDdj7+DlOHZjmTf1GVqK4Z/vAyh21zAERDzsm/0CMqPCnWvgg8P9j+2u2nGHBQpkHzTwyiLUPm8lr13ntSswQlag8pgYIqwJidJPtYl1pXmMOo2ygDWvwGSD4X7O1W9FuJoW0MSVZJspnYkk22LN1LZFVtg6s9Ud5Jj3/JDH+tHSryMBauRlOxNiTE0AV5DgntCoKs0/vAT7Nw1QbH91sr7YuFYnRVteNh2619fRJrvJfc0a5JQ3NMIkxqaLz699VuQXARkF78RvIHnoS7L9M2wDvmw8+P3jJ6jamgPPrQUYt0aD+slW1NAa6hTI9VXN2oqVJHX4k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MinimalHostsBlocker
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
