env:
  global:
    - secure: XuOjz3UuNBDiHLqvm6TQ+E7IHIX0rWafkwoIWXdWP+yH50J1k4lBclsaklyA8jFMI1t87Epd+n2agFoKPi3lc68mg39uz86U5JVs+qShHLwscnWbnFp+n64KEIEY5rEFCRL5X2vGURqx2KgDSYKDRdEtMZ2CLe9BqWl+9abpByiQwF52bdw2I7z8DpEpvpobEea1oobDk2fpH+qCqC4xojHOQ/xqA1CygTDV3/HAR2SGlTNg/tAUlD8nxAMtR2kFlC2MhmwV8BfU3OPE79F+XnmQq93jByYnMmvMeHYEx/SrYog51Skv4N9HqpwuYBefXMURm4IxdEf12RVHcjyNnU6YrlfG6g3wITn4fQXTnIhXVY6cM97LOC2dgWOYbIXsXXDFOBaymll7KhI3yfgsGU23Aih92fnrIxnBSCnLWSFB557zCQcYSlkP7/NBIMKkl4jOxGpFhHU3X77bZ0CKdJ9YAxRVf4i4ek90vx/LJ8Vxs/FleuVJzgB0+FZWnvuMMFn0+YEZGouNmsW6XYQYIsAso0H7qt/lVQZkD0c/ih9PGEegHEpKzuVvOcwMrplyJqKn62dtYIXtFmXHVte7ndZ1Dbj9W3R16Q6ni5v2xWklS57oVS9iOTgbiMtozML+6rgSSDtcpvF04OVH8IEDzcWLUKL+ccKtIJZhi0lZ5J4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/MinimalHostsBlocker
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
